In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x, y, x+y, x*y, x/y, x**y

(tensor(3.), tensor(2.), tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [8]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [9]:
x[2]

tensor(2)

In [10]:
len(x)

3

In [11]:
x.shape

torch.Size([3])

In [12]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [13]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [14]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [15]:
len(A), A.shape

(3, torch.Size([3, 3]))

In [16]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5], [8,8,8]])
len(A)

4

In [17]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [18]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A,B,A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [19]:
A*B # elementwise product

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [20]:
a = 2
X = torch.arange(24).reshape(2,3,4)
X, a+X

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]))

In [21]:
(a*X),(a*X).shape

(tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [22]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [24]:
A, A.shape, A.sum(axis=0), A.sum(axis=0).shape #axis 0 is row 0

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([3., 5., 7.]),
 torch.Size([3]))

In [25]:
A, A.shape, A.sum(axis=1), A.sum(axis=1).shape #axis 0 is row 0

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([ 3., 12.]),
 torch.Size([2]))

In [26]:
A.sum(axis=[0, 1]), A.sum(), A.sum(axis=[0, 1]) == A.sum()

(tensor(15.), tensor(15.), tensor(True))

In [27]:
A.mean(), A.sum(), A.numel(), A.sum()/A.numel() # numel = num of elements

(tensor(2.5000), tensor(15.), 6, tensor(2.5000))

In [32]:
A, A.mean(axis=0), A.sum(axis=0), A.shape[0], A.sum(axis=0) / A.shape[0]

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([1.5000, 2.5000, 3.5000]),
 tensor([3., 5., 7.]),
 2,
 tensor([1.5000, 2.5000, 3.5000]))

In [33]:
sum_A = A.sum(axis=1, keepdims=True)
A, A.shape, sum_A, sum_A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [36]:
A.sum(axis=1), A.sum(axis=1).shape

(tensor([ 3., 12.]), torch.Size([2]))

In [37]:
A, sum_A, A / sum_A

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 3.],
         [12.]]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167]]))

In [38]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [39]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [41]:
x*y, torch.sum(x * y)

(tensor([0., 1., 2.]), tensor(3.))

In [42]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [43]:
A, x, A@x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]),
 tensor([ 5., 14.]))

In [46]:
B = torch.ones(3, 4)
A, B, torch.mm(A, B), A@B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [47]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [48]:
torch.abs(u).sum()

tensor(7.)

In [50]:
torch.ones((4, 9)), torch.norm(torch.ones((4, 9)))

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))